#ifndef _DIRECTXGLOBALS_H_
#define _DIRECTXGLOBALS_H_

#include "DirectX9/Include/d3d9.h"

#define CUSTOMFVF (D3DFVF_XYZ | D3DFVF_NORMAL)
struct CUSTOMVERTEX { FLOAT X, Y, Z; D3DVECTOR NORMAL; };





#endif _DIRECTXGLOBALS_H_

